name: Go
on:
- push
jobs:
  build:
    name: Build
    runs-on: [ubuntu-18.04]
    steps:
    - name: Set up Go 1.13
      id: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        PATH=~/go/bin:$PATH
        if ! type gox >/dev/null 2>&1; then
          go get -u github.com/mitchellh/gox
        fi
        make

    - name: create archive zip
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: release

  archive_them:
    name: Archive
    runs-on: [ubuntu-18.04]
    needs: build
    strategy:
      matrix:
        binary_filename:
        - kubeoidc_darwin_amd64
        - kubeoidc_linux_amd64
        - kubeoidc_linux_amd64.exe
    steps:
    - name: fetch build artifact
      uses: actions/download-artifact@v1
      with:
        name: binaries
    - name: Archive build output
      uses: actions/upload-artifact@v1
      with:
        name: binary
        path: binaries/${{ matrix.binary_filename }}
