name: Go
on:
- push
jobs:
  build:
    name: Build
    runs-on: [ubuntu-18.04]
    steps:
    - name: Set up Go 1.13
      id: go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        set -x
        if ! type gox >/dev/null 2>&1; then
          go get -u github.com/mitchellh/gox
          ls -la ~/go/bin
        fi
        if ! type gox >/dev/null 2>&1; then
          PATH=~/go/bin:$PATH
          gox -version || true
        fi
        make

    - name: Archive build output
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: release/*
